/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Arquivo;
import controller.BancoDeDados;
import controller.FluxoCaixa;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author fhmbe
 */
public class FluxoDeCaixa extends javax.swing.JInternalFrame {

    /**
     * Creates new form FluxoDeCaixa
     */
    public FluxoDeCaixa() throws FileNotFoundException {
        this.file = new Arquivo();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        listFluxo = new java.awt.List();
        btnGerar = new javax.swing.JButton();
        txtData = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNomeFluxo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fluxo"));

        btnGerar.setText("Gerar Fluxo de Caixa");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        jLabel1.setText("Data:");

        jLabel2.setText("Nome:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(listFluxo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeFluxo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(btnGerar)
                        .addGap(63, 63, 63))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(listFluxo, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNomeFluxo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnGerar)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    BancoDeDados bd = new BancoDeDados();
    private float contasAPagar = 0;
    private float contasPagas = 0;
    private float contasAReceber = 0;
    private float contasRecebidas = 0;
    private float custosValor = 0;
    private float bancoSaldos = 0;
    private float bancoDebitos = 0;
    private float totalLucro = 0;
    Arquivo file;

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        // TODO add your handling code here: 
        this.contasAPagar = 0;
        this.contasPagas = 0;
        this.contasAReceber = 0;
        this.contasRecebidas = 0;
        this.custosValor = 0;
        this.bancoSaldos = 0;
        this.bancoDebitos = 0;
        this.totalLucro = 0;
        this.listFluxo.clear();
        String cap, cp, car, cr, ca, sb;
        //String data = "";
        FluxoCaixa fc;
        try{
        if (this.txtData.getText().matches("[0-9]{2}[/][0-9]{2}[/][0-9]{4}") == false) {
            JOptionPane.showMessageDialog(null, "Formato de data inválido, seguir o formato: dd/mm/aaaa");
        } else {
            this.listFluxo.add("--------------------------------------------------");
            for (int i = 0; i < bd.buscarContasAPagar().size(); i++) {
                if (bd.buscarContasAPagar().get(i) != null && bd.buscarContasAPagar().get(i).getContasPagar() > 0) {
                    this.contasAPagar += bd.buscarContasAPagar().get(i).getContasPagar();
                    cap = "Títulos serem Pagos: " + bd.buscarContasAPagar().get(i).getNome() + "  |  R$" + bd.buscarContasAPagar().get(i).getContasPagar() + "  |  "
                            + bd.buscarContasAPagar().get(i).getData();
                    this.listFluxo.add(cap);

                } else if (bd.buscarContasAPagar().get(i) != null && bd.buscarContasAPagar().get(i).getContasPagas() > 0) {
                    this.contasPagas += bd.buscarContasAPagar().get(i).getContasPagas();
                    cp = "Títulos Pagos: " + bd.buscarContasAPagar().get(i).getNome() + "  |  R$" + bd.buscarContasAPagar().get(i).getContasPagas() + "  |  "
                            + bd.buscarContasAPagar().get(i).getData();
                    this.listFluxo.add(cp);
                }
            }

            for (int i = 0; i < bd.buscarContasAReceber().size(); i++) {
                if (bd.buscarContasAReceber().get(i) != null && bd.buscarContasAReceber().get(i).getContasReceber() > 0) {
                    this.contasAReceber += bd.buscarContasAReceber().get(i).getContasReceber();
                    car = "Títulos a serem Recebidos: " + bd.buscarContasAReceber().get(i).getNome() + "  |  R$" + bd.buscarContasAReceber().get(i).getContasReceber() + "  |  "
                            + bd.buscarContasAReceber().get(i).getData();
                    this.listFluxo.add(car);

                } else if (bd.buscarContasAReceber().get(i) != null && bd.buscarContasAReceber().get(i).getContasRecebidas() > 0) {
                    this.contasRecebidas += bd.buscarContasAReceber().get(i).getContasRecebidas();
                    cr = "Títulos Recebidos: " + bd.buscarContasAReceber().get(i).getNome() + "  |  R$" + bd.buscarContasAReceber().get(i).getContasRecebidas() + "  |  "
                            + bd.buscarContasAReceber().get(i).getData();
                    this.listFluxo.add(cr);
                }
            }

            for (int i = 0; i < bd.buscarGestaoDeCusto().size(); i++) {
                if (bd.buscarGestaoDeCusto().get(i) != null) {
                    this.custosValor += bd.buscarGestaoDeCusto().get(i).getValor();
                    ca = "Custos adicionais: " + bd.buscarGestaoDeCusto().get(i).getNome() + "  |  " + bd.buscarGestaoDeCusto().get(i).getValor();
                    this.listFluxo.add(ca);
                }
            }

            for (int i = 0; i < bd.buscarExtrato().size(); i++) {
                if (bd.buscarExtrato().get(i) != null) {
                    this.bancoSaldos += bd.buscarExtrato().get(i).getEntrada();
                    sb = "Saldos Bancários: " + bd.buscarExtrato().get(i).getNome() + "  |  " + bd.buscarExtrato().get(i).getEntrada();
                    this.listFluxo.add(sb);
                }
            }

            this.listFluxo.add("---------------------RESUMO-----------------------");
            this.listFluxo.add("Títulos a pagar: R$" + this.contasAPagar);
            this.listFluxo.add("Títulos Pagos: R$" + this.contasPagas);
            this.listFluxo.add("--------------------------------------------------");
            this.listFluxo.add("Títulos a receber: R$" + this.contasAReceber);
            this.listFluxo.add("Título recebidos: R$" + this.contasRecebidas);
            this.listFluxo.add("--------------------------------------------------");
            this.listFluxo.add("Custos: R$" + this.custosValor);
            this.listFluxo.add("--------------------------------------------------");
            this.totalLucro = this.contasRecebidas + this.bancoSaldos - this.contasPagas - this.custosValor;
            this.listFluxo.add("Fechamento:");
            this.listFluxo.add("");
            this.listFluxo.add("Lucro: R$" + this.totalLucro);
            this.listFluxo.add("Contas a receber: R$" + this.contasAReceber);
            this.listFluxo.add("Contas a pagar: R$" + this.contasAPagar);
            if (this.totalLucro > 0) {
                this.listFluxo.add("+------------------------+");
                this.listFluxo.add("  Status: Teve Lucro");
                fc = new FluxoCaixa(this.txtNomeFluxo.getText(), this.totalLucro, 0, this.txtData.getText());
                this.listFluxo.add("+------------------------+");
            } else if (this.totalLucro < 0) {
                this.listFluxo.add("+------------------------+");
                this.listFluxo.add("  Status: Teve Prejuíso");
                fc = new FluxoCaixa(this.txtNomeFluxo.getText(), 0, this.totalLucro, this.txtData.getText());
                this.listFluxo.add("+------------------------+");
            } else {
                this.listFluxo.add("+------------------------+");
                this.listFluxo.add("  Status: Zerado");
                fc = new FluxoCaixa(this.txtNomeFluxo.getText(), 0, 0, this.txtData.getText());
                this.listFluxo.add("+------------------------+");
            }
            bd.inserirFluxoCaixa(fc);
            file.WriteFile("---------------------RESUMO-----------------------" + "\n" + "Títulos a pagar: R$" + this.contasAPagar + "\n" + "Títulos Pagos: R$" + this.contasPagas + 
                    "\n" + "--------------------------------------------------" + "\n" + "Títulos a receber: R$" + this.contasAReceber + "\n" + "Títulos recebidos: R$" + this.contasRecebidas +
                    "\n" + "--------------------------------------------------" + "\n" + "Custos: R$" + this.custosValor +  "\nSaldos: R$" + this.bancoSaldos + "\n" + 
                            "--------------------------------------------------" + "\n" + "Lucro: R$" + this.totalLucro + "\nData: " + this.txtData.getText());
        }
        } catch (IOException ex) {
            Logger.getLogger(Relatorio.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "Erro: " + ex);
        }
    }//GEN-LAST:event_btnGerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private java.awt.List listFluxo;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtNomeFluxo;
    // End of variables declaration//GEN-END:variables
}
